### ISSUE TITLE
Please update the version of the plugin on plugins.cloudfoundry.org

### ISSUE THREAD

**Issue by jtuchscherer** [ECSTeam/buildpack-usage#2]
Hi there,

thanks for the great plugin. Could you please upgrade the [official plugin repository](https://plugins.cloudfoundry.org/)? The version linked there is still 1.0 and has the problem where the call to `cmd.UI.Ok` is panicking. Hence, the officially available plugin fails silently.

I manually installed v1.0.4 and everything works fine.

Thanks again

**Comment by jghiloni** [comment]
Thanks for pointing this out Johannes! The repo has been updated.
